version: '3.3'
services:
    home-assistant:
        container_name: homeassistant
        privileged: false
        restart: unless-stopped
        environment:
            - TZ=Europe/Berlin
        volumes:
            - './config:/config'
        image: 'ghcr.io/home-assistant/home-assistant:stable'
        ports:
            - 8123:8123
